# Generated by Django 5.1.9 on 2025-05-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="object_id",
            field=models.PositiveIntegerField(
                db_index=True, help_text="The ID of the specific purchasable item"
            ),
        ),
    ]
