# Generated by Django 6.0 on 2025-12-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_source",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="How did you hear about us?",
            ),
        ),
    ]
