# Generated by Django 6.0.1 on 2026-01-25 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_referral_source"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
