# Generated by Django 6.0.1 on 2026-01-26 00:03

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_managers_remove_user_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session_token",
            field=models.CharField(
                db_index=True,
                default=apps.users.models.generate_session_token,
                max_length=255,
                unique=True,
            ),
        ),
    ]
