# Generated by Django 6.0.2 on 2026-02-25 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scraper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        choices=[
                            ("govexec.news", "GovExec"),
                            ("defenseone.news", "Defense One"),
                            ("globaltimes.news", "Global Times"),
                            ("koreaherald.news", "Korea Herald"),
                            ("kyivindependent.news", "Kyiv Independent"),
                        ],
                        max_length=240,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("auto_publish", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=240, unique=True)),
                (
                    "base_url",
                    models.CharField(max_length=1000, verbose_name="Starting url"),
                ),
                ("category", models.CharField(max_length=240, verbose_name="Category")),
                (
                    "section_container",
                    models.CharField(
                        blank=True,
                        max_length=240,
                        null=True,
                        verbose_name="Section Container",
                    ),
                ),
                (
                    "article_item",
                    models.CharField(
                        max_length=240, verbose_name="Article Selector Path"
                    ),
                ),
                (
                    "href_selector",
                    models.CharField(max_length=240, verbose_name="Href selector"),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("total_runs", models.IntegerField(default=0)),
                ("successful_runs", models.IntegerField(default=0)),
                ("failed_runs", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000, unique=True)),
                (
                    "query_params",
                    models.TextField(
                        blank=True, help_text="URL query parameters", null=True
                    ),
                ),
                ("category", models.IntegerField()),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Success", "Success"),
                            ("Failed", "Failed"),
                        ],
                        default="Not Started",
                        max_length=20,
                    ),
                ),
                ("scraped_text", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scraper",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="scraper.scraper",
                    ),
                ),
            ],
        ),
    ]
