# Generated by Django 6.0.2 on 2026-02-25 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scraper",
            name="auto_publish",
        ),
    ]
